/**
 * Integration tests for the IBM Db2 DDL dialect.
 * Target: Db2 LUW 11.1+
 *
 * QSQL syntax notes:
 *   - Table-level directives go on the table name line: "employees /api full+hks"
 *   - Column-level directives go on the column line: "  email /unique"
 */
import { describe, test, expect, beforeEach } from 'vitest';
import { toDDL } from '../../src/ddl.js';
import { resetSeed } from '../../src/utils/sample.js';

beforeEach(() => { resetSeed(); });

const DB2 = '# settings = {"dialect":"db2","inserts":"no"}';

function ddl(input: string): string {
    return toDDL(input + '\n' + DB2);
}

// ── §1 Type mapping ────────────────────────────────────────────────────────────

describe('§1 Db2 type mapping', () => {

    test('varchar uses VARCHAR not VARCHAR2', () => {
        const out = ddl('employees\n  first_name vc50\n  last_name');
        expect(out).toContain('varchar(50)');
        expect(out).not.toContain('varchar2');
    });

    test('default string is varchar(4000) not varchar2', () => {
        const out = ddl('employees\n  notes');
        expect(out).toContain('varchar(4000)');
        expect(out).not.toContain('varchar2');
    });

    test('num maps to decimal', () => {
        const out = ddl('employees\n  salary num');
        expect(out).toContain('decimal(15,4)');
    });

    test('number with spec maps to decimal(p,s)', () => {
        const out = ddl('invoices\n  total_amount num(12,2)');
        expect(out).toContain('decimal(12,2)');
    });

    test('date maps to date', () => {
        const out = ddl('events\n  event_date d');
        expect(out).toContain('event_date');
        expect(out).toContain(' date');
    });

    test('timestamp maps to timestamp', () => {
        const out = ddl('events\n  created_at ts');
        expect(out).toContain('timestamp');
    });

    test('clob maps to clob', () => {
        const out = ddl('docs\n  body clob');
        expect(out).toContain('clob');
    });

    test('boolean maps to boolean (Db2 11.5+), no Y/N check constraint', () => {
        const out = ddl('flags\n  is_active bool');
        expect(out).toContain('boolean');
        expect(out).not.toContain("in ('Y','N')");
    });

    test('json maps to json', () => {
        const out = ddl('configs\n  payload json');
        expect(out).toContain('json');
    });

});

// ── §2 PK and identity ─────────────────────────────────────────────────────────

describe('§2 Primary key', () => {

    test('default PK uses GENERATED ALWAYS AS IDENTITY', () => {
        const out = ddl('employees\n  name');
        expect(out).toContain('generated always as identity');
        expect(out).not.toContain('generated by default on null');
        expect(out).not.toContain('number generated');
    });

    test('PK is INTEGER not NUMBER', () => {
        const out = ddl('employees\n  name');
        expect(out).toMatch(/\bid\b.*integer/);
        expect(out).not.toMatch(/\bid\b.*number/i);
    });

    test('PK constraint name ends with _pk', () => {
        const out = ddl('employees\n  name');
        expect(out).toContain('constraint employees_id_pk primary key');
    });

    test('pk:seq generates Db2 sequence and DEFAULT NEXT VALUE FOR', () => {
        const out = toDDL('employees\n  name\n' + DB2 + '\n# settings = {"pk":"seq"}');
        expect(out).toContain('create sequence  employees_seq start with 1 increment by 1');
        expect(out).toContain('default next value for employees_seq');
    });

});

// ── §3 System functions ────────────────────────────────────────────────────────

describe('§3 Db2 system functions', () => {

    test('no SYSDATE in DDL output', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).not.toContain('sysdate');
        expect(out).not.toContain('SYSDATE');
    });

    test('audit columns use timestamp type not date', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('timestamp');
    });

    test('audit trigger uses CURRENT TIMESTAMP not SYSDATE', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('current timestamp');
        expect(out).not.toContain('sysdate');
    });

    test('audit trigger uses CURRENT USER not v(\'APP_USER\')', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('current user');
        expect(out).not.toContain("v('APP_USER')");
    });

});

// ── §4 Table structure ─────────────────────────────────────────────────────────

describe('§4 Table DDL structure', () => {

    test('basic table has CREATE TABLE', () => {
        const out = ddl('employees\n  name');
        expect(out).toContain('create table employees');
    });

    test('FK column generates integer type', () => {
        const out = ddl('departments\n  name\nemployees\n  department_id /fk departments\n  name');
        expect(out).toContain('department_id');
        expect(out).toContain('integer');
    });

    test('FK constraint uses standard REFERENCES syntax', () => {
        const out = ddl('departments\n  name\nemployees\n  department_id /fk departments\n  name');
        expect(out).toContain('references departments');
    });

    test('UNIQUE constraint generates Db2 syntax', () => {
        const out = ddl('employees\n  email /unique');
        expect(out).toContain('constraint employees_email_unq unique');
    });

    test('NOT NULL generates standard syntax', () => {
        const out = ddl('employees\n  name /nn');
        expect(out).toContain('not null');
    });

    test('no Oracle-specific keywords in output', () => {
        const out = ddl('employees\n  name\n  salary num(12,2)\n  hire_date d');
        expect(out).not.toContain('VARCHAR2');
        expect(out).not.toContain('NUMBER');
        expect(out).not.toContain('cascade constraints');
    });

});

// ── §5 Indexes ─────────────────────────────────────────────────────────────────

describe('§5 Indexes', () => {

    test('FK index uses CREATE INDEX', () => {
        const out = ddl('departments\n  name\nemployees\n  department_id /fk departments\n  name');
        expect(out).toContain('create index employees_i1 on employees (department_id)');
    });

    test('explicit /idx generates CREATE INDEX', () => {
        const out = ddl('employees\n  name /idx');
        expect(out).toContain('create index employees_i1 on employees (name)');
    });

});

// ── §6 DROP statements ─────────────────────────────────────────────────────────

describe('§6 DROP statements', () => {

    test('drop table uses IF EXISTS not Oracle cascade constraints', () => {
        const out = toDDL('employees\n  name\n' + DB2 + '\n# settings = {"drop":"yes"}');
        expect(out).toContain('drop table if exists employees');
        expect(out).not.toContain('cascade constraints');
    });

});

// ── §7 Trigger generation ──────────────────────────────────────────────────────

describe('§7 Db2 triggers', () => {

    test('BEFORE INSERT trigger uses REFERENCING NEW AS n syntax', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('referencing new as n');
        expect(out).not.toContain(':new.');
    });

    test('BEFORE UPDATE trigger uses REFERENCING NEW AS n OLD AS o', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('referencing new as n old as o');
    });

    test('trigger uses SET not assignment operator', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('set n.');
        expect(out).not.toContain(':=');
    });

    test('trigger body ends with @', () => {
        const out = ddl('employees /auditcols\n  name');
        expect(out).toContain('end @');
    });

    test('row version trigger sets row_version = 1 on insert', () => {
        const out = ddl('employees /rowversion\n  name');
        expect(out).toContain('set n.row_version = 1');
    });

    test('row version trigger increments on update', () => {
        const out = ddl('employees /rowversion\n  name');
        expect(out).toContain('set n.row_version = coalesce(o.row_version, 0) + 1');
    });

});
